version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/benchmark"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/dashboard"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/producer"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/worker"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
