version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/producer"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/worker"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1

  - package-ecosystem: "npm"
    directory: "/benchmark"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1